export enum KpiEnum {
  SUCCESS_RATE_TRANSFER_ORANGE_CI = "success_rate__transfer_orange_ci",
  SUCCESS_RATE_TRANSFER_MTN_CI = "success_rate__transfer_mtn_ci",
  SUCCESS_RATE_TRANSFER_MOOV_CI = "success_rate__transfer_moov_ci",
  SUCCESS_RATE_TRANSFER_WAVE_CI = "success_rate__transfer_wave_ci",
  SUCCESS_RATE_PAYMENT_ORANGE_CI = "success_rate__payment_orange_ci",
  SUCCESS_RATE_PAYMENT_MTN_CI = "success_rate__payment_mtn_ci",
  SUCCESS_RATE_PAYMENT_MOOV_CI = "success_rate__payment_moov_ci",
  SUCCESS_RATE_PAYMENT_WAVE_CI = "success_rate__payment_wave_ci",
  SUCCESS_RATE_TRANSFER_ALL = "success_rate__transfer_all",
  SUCCESS_RATE_PAYMENT_ALL = "success_rate__payment_all",
  VOLUME_XAF = "volume_xaf",
  VOLUME_XOF = "volume_xof",
  TRASACTION_LAST_ONE = "transaction_last_one",
}
