version: "3.7"

services:
    data-kpi:
        container_name: data-kpi
        build:
            context: ${APP_ROOT}
            dockerfile: infra/docker/Dockerfile
            args:
                APP_ENV: "dev"
                NODE_ENV: "dev"
                NPM_TOKEN: ${NPM_TOKEN}
                BUILD_ARCH: ${BUILD_ARCH}
        environment:
            APP_ENV: "dev"
            NODE_ENV: "dev"
            NPM_TOKEN: ${NPM_TOKEN}
        env_file:
            - "${APP_ROOT}/infra/config/.env"
        ports:
            - 3560:3000
            - 3561:9229
        volumes:
           - "${APP_ROOT}:/app/" # allow watch dev mode
        entrypoint: /bin/sh -c "npm install && npm run start:debug"
        networks:
            - hub2_network
networks:
    hub2_network:
        external: true
        name: hub2_network
